export const SET = 'SET'
export const DELETE = 'DELETE'
export const ADD_VALUE = 'ADD_VALUE'
export const ADD_VALUES = 'ADD_VALUES'
export const DELETE_BY_PATHS = 'DELETE_BY_PATHS'
export const COPY_BY_PATHS = 'COPY_BY_PATHS'
export const MOVE_BY_PATHS = 'MOVE_BY_PATHS'
